[build-system]
requires = ["uv_build>=0.12.23,<0.13"]
build-backend = "uv_build"

[project]
name = "interactive-figure"
version = "0.6.1"
description = "Create interactive Matplotlib figures!"
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [
  { name = "Teun Mathijssen", email = "teun.c.mathijssen@gmail.com" },
]
classifiers = [
  "Framework :: Matplotlib",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Visualization"
]
dependencies = ["matplotlib>=3.6"]

[project.urls]
Documentation = "https://teuncm.github.io/interactive-figure/autoapi/interactive_figure/interactive_figure/index.html"
Issues = "https://github.com/teuncm/interactive-figure/issues"
Source = "https://github.com/teuncm/interactive-figure"

[dependency-groups]
dev = [{ include-group = "lint" }]
docs = [
  "sphinx",
  "sphinx-rtd-theme",
  "sphinx-book-theme",
  "sphinx-autoapi",
]
lint = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "ruff>=0.0.243",
]

[tool.black]
target-version = ["py311"]
line-length = 120
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["interactive_figure"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
